blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions ✍️
    url: https://github.com/SamErde/PinnedApps/discussions
    about: Please use GitHub discussions for any questions.
#  - name: Basic FAQs ❓
#    url: https://github.com/SamErde/PinnedApps/wiki/FAQs
#    about: Answers to the Basic Frequently Asked Questions
