name: 👷‍♂️ Auto-Assign Issues and PRs
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: '👷‍♂️ Auto-assign Issue'
      uses: pozil/auto-assign-issue@v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          numOfAssignee: 1
          assignees: ${{ vars.DEFAULT_ISSUE_ASSIGNEE }}
          allowSelfAssign: true
    - name: '👷‍♂️ Auto-assign PR'
      uses: pozil/auto-assign-issue@v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          numOfAssignee: 1
          assignees: ${{ vars.DEFAULT_PR_ASSIGNEE }}
          allowSelfAssign: true
